import { Category, CourseLevel } from './types';

export const COURSE_DATA: Category[] = [
  {
    id: 'recommended',
    title: '🚀 Key Recommendations',
    description: 'Curated paths specifically for Microsoft Azure, AI, and Cloud technologies.',
    courses: [
      {
        id: 'ml-concepts',
        title: 'Introduction to Machine Learning Concepts',
        topics: ['ML Fundamentals', 'ML Types', 'Training/Evaluation', 'Deep Learning'],
        level: CourseLevel.Beginner,
        link: 'https://learn.microsoft.com/training/modules/fundamentals-machine-learning/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        details: 'Understand the core principles of ML: Regression, Classification, and Clustering, and how to evaluate models.',
        prerequisites: ['Basic Math'],
        isRecommended: true,
      },
      {
        id: 'web-start',
        title: 'Get started with web development using Visual Studio Code (HTML,CSS,JS)',
        topics: ['HTML', 'CSS', 'JavaScript', 'Web Development', 'Browser DevTools'],
        level: CourseLevel.Beginner,
        link: 'https://learn.microsoft.com/training/modules/get-started-with-web-development/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        details: 'Understand how the internet works and build your first static website using VS Code.',
        prerequisites: ['No prior experience required'],
        isRecommended: true
      },
      {
        id: 'rec-genai-intro',
        title: 'Introduction to Generative AI and Agents',
        topics: ['Generative AI', 'LLMs', 'Prompting', 'AI Agents', 'Agentic AI'],
        level: CourseLevel.Beginner,
        link: 'https://learn.microsoft.com/training/modules/fundamentals-generative-ai/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        isRecommended: true,
        details: 'Understand how Large Language Models (LLMs) work, how to craft effective prompts, and the emerging field of autonomous AI agents.',
        prerequisites: ['No prior experience required'],
      },
      {
        id: 'cloud-intro',
        title: 'Introduction to Cloud Infrastructure: Describe Cloud Concepts',
        topics: ['Cloud Computing', 'Shared Responsibility Model', 'Azure Basics'],
        level: CourseLevel.Beginner,
        link: 'https://learn.microsoft.com/training/paths/microsoft-azure-fundamentals-describe-cloud-concepts/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        details: 'Explains IaaS, PaaS, SaaS models, and the benefits of cloud scalability and high availability.',
        prerequisites: ['No prior experience required'],
        isRecommended: true,
      },
      {
        id: 'py-vscode',
        title: 'Getting Started with Python in VS Code',
        topics: ['Python Setup', 'VS Code', 'Debugging', 'Virtual Environments'],
        level: CourseLevel.Beginner,
        link: 'https://learn.microsoft.com/shows/visual-studio-code/getting-started-with-python-in-vs-code-official-video?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        details: 'Learn to use the Python extension for VS Code, including linting, formatting, and running Jupyter notebooks.',
        prerequisites: ['No prior experience required'],
        isRecommended: true,
      },
      {
        id: 'ml-cert',
        title: 'Microsoft Certified: Microsoft Data Scientist Associate',
        topics: ['Data Science', 'ML Models', 'MLflow', 'Azure AI Services', 'Python'],
        level: CourseLevel.Intermediate,
        link: 'https://learn.microsoft.com/credentials/certifications/azure-data-scientist/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        details: 'Certification path for data scientists applying their knowledge of data exploration and model training on Azure.',
        prerequisites: ['DP-100 Skills'],
        isRecommended: true,
      },
    ]
  },
  {
    id: 'microsoft-learn',
    title: '⊞ Microsoft Learn — Featured Paths',
    description: 'Official Microsoft courses: AI, Cloud, Dev, Python, C#, and more. Free, self-paced, and industry-recognized.',
    courses: [
      {
        id: 'ms-az900-cert',
        title: 'Microsoft Azure Fundamentals (AZ-900)',
        topics: ['Azure Fundamentals', 'Cloud Concepts', 'Azure Services', 'Security', 'Compliance', 'Cost Management'],
        level: CourseLevel.Beginner,
        link: 'https://learn.microsoft.com/en-us/credentials/certifications/azure-fundamentals/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        isRecommended: true,
        isMicrosoft: true,
        details: 'The most popular cloud certification for beginners. Validates core Azure knowledge including cloud concepts, services, security, and pricing.',
        prerequisites: ['No prior experience required'],
      },
      {
        id: 'ms-ai-900-path',
        title: 'AI Fundamentals (AI-900) Learning Path',
        topics: ['AI Fundamentals', 'Machine Learning', 'Computer Vision', 'NLP', 'Generative AI', 'Azure AI Services'],
        level: CourseLevel.Beginner,
        link: 'https://learn.microsoft.com/en-us/training/paths/get-started-with-artificial-intelligence-on-azure/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        isRecommended: true,
        isMicrosoft: true,
        details: 'The official Microsoft Learning Path for the AI-900 exam.',
        prerequisites: ['No prior experience required'],
      },
      {
        id: 'ms-python-beginner',
        title: 'Python for Beginners',
        topics: ['Python Basics', 'Variables', 'Functions', 'Lists', 'Loops', 'VS Code', 'Modules'],
        level: CourseLevel.Beginner,
        link: 'https://learn.microsoft.com/en-us/training/paths/beginner-python/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        isRecommended: true,
        isMicrosoft: true,
        details: 'Microsoft\'s official beginner Python path featuring short video lessons.',
        prerequisites: ['No prior experience required'],
      },
      {
        id: 'ms-github-copilot-intro',
        title: 'Introduction to GitHub Copilot',
        topics: ['GitHub Copilot', 'AI Pair Programming', 'Code Generation', 'VS Code', 'Productivity', 'Testing'],
        level: CourseLevel.Beginner,
        link: 'https://learn.microsoft.com/en-us/training/modules/introduction-to-github-copilot/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        isRecommended: true,
        isMicrosoft: true,
        details: 'Learn how GitHub Copilot uses AI to generate code.',
        prerequisites: ['Basic programming knowledge'],
      },
      {
        id: 'ms-typescript-path',
        title: 'Build JavaScript Applications with TypeScript',
        topics: ['TypeScript', 'Static Types', 'Interfaces', 'Generics', 'Enums', 'Modules', 'Decorators'],
        level: CourseLevel.Intermediate,
        link: 'https://learn.microsoft.com/en-us/training/paths/build-javascript-applications-typescript/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        isRecommended: true,
        isMicrosoft: true,
        details: 'Master TypeScript—Microsoft\'s own language that adds static typing to JavaScript.',
        prerequisites: ['JavaScript Basics'],
      },
      {
        id: 'ms-ai-agents',
        title: 'Get Started with AI Agent Development',
        topics: ['AI Agents', 'Azure AI Foundry', 'Semantic Kernel', 'AutoGen', 'Tool Use', 'Agentic Workflows'],
        level: CourseLevel.Beginner,
        link: 'https://learn.microsoft.com/en-us/training/modules/ai-agent-fundamentals/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        isRecommended: true,
        isMicrosoft: true,
        details: 'Understand what AI agents are and how to build them on Azure.',
        prerequisites: ['Basic Python', 'Generative AI Concepts'],
      },
      {
        id: 'ms-foundry-sdk',
        title: 'Develop an AI App with Microsoft',
        topics: ['Azure AI Foundry', 'AI App Development', 'LLMs', 'REST APIs', 'Prompt Flow', 'Deployment'],
        level: CourseLevel.Beginner,
        link: 'https://learn.microsoft.com/en-us/training/modules/ai-foundry-sdk/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        isRecommended: true,
        isMicrosoft: true,
        details: 'Build fully functional AI applications using the Azure AI Foundry SDK.',
        prerequisites: ['Python Basics'],
      },
      {
        id: 'ms-csharp-foundations',
        title: 'C# Foundations for Absolute Beginners',
        topics: ['C# Syntax', 'Variables', 'Methods', 'OOP', 'Console Apps', '.NET', 'Debugging'],
        level: CourseLevel.Beginner,
        link: 'https://learn.microsoft.com/en-us/training/paths/get-started-c-sharp-part-1/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        isRecommended: true,
        isMicrosoft: true,
        details: 'Start from zero with C# and .NET.',
        prerequisites: ['No prior experience required'],
      },
      {
        id: 'ms-ml-azure-path',
        title: 'Create Machine Learning Models',
        topics: ['Azure Machine Learning', 'Training', 'MLflow', 'Automated ML', 'Pipelines', 'Model Deployment'],
        level: CourseLevel.Intermediate,
        link: 'https://learn.microsoft.com/en-us/training/paths/create-machine-learn-models/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        isRecommended: true,
        isMicrosoft: true,
        details: 'End-to-end path for building, training, evaluating, and deploying ML models.',
        prerequisites: ['Python', 'Basic ML Concepts'],
      },
      {
        id: 'ms-power-bi',
        title: 'Get Started Building with Power BI',
        topics: ['Power BI Desktop', 'Data Visualization', 'Reports', 'Dashboards', 'DAX', 'Data Modeling'],
        level: CourseLevel.Beginner,
        link: 'https://learn.microsoft.com/en-us/training/modules/get-started-with-power-bi/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        isRecommended: true,
        isMicrosoft: true,
        details: 'Learn to create interactive charts, reports, and dashboards.',
        prerequisites: ['No prior experience required'],
      },
      {
        id: 'ms-devops',
        title: 'Evolve Your DevOps Practices',
        topics: ['DevOps', 'Azure DevOps', 'CI/CD', 'Git', 'GitHub Actions', 'Agile', 'Automation'],
        level: CourseLevel.Beginner,
        link: 'https://learn.microsoft.com/en-us/training/paths/evolve-your-devops-practices/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        isRecommended: true,
        isMicrosoft: true,
        details: 'Understand DevOps culture and implement it with Azure DevOps.',
        prerequisites: ['Basic programming knowledge'],
      },
      {
        id: 'ms-responsible-ai',
        title: 'Responsible Generative AI',
        topics: ['Responsible AI', 'Content Safety', 'Bias Mitigation', 'AI Ethics', 'Evaluation', 'Azure AI Foundry'],
        level: CourseLevel.Intermediate,
        link: 'https://learn.microsoft.com/en-us/training/modules/responsible-ai-studio/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        isRecommended: true,
        isMicrosoft: true,
        details: 'Learn to build and deploy responsible generative AI.',
        prerequisites: ['Basic Generative AI Knowledge'],
      },
      {
        id: 'ms-prepare-ai-dev',
        title: 'Plan and Prepare to Develop AI Solutions',
        topics: ['Azure AI Services', 'AI Solution Architecture', 'Resource Planning', 'SDK Setup', 'Security', 'Monitoring'],
        level: CourseLevel.Beginner,
        link: 'https://learn.microsoft.com/en-us/training/modules/prepare-azure-ai-development/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        isRecommended: true,
        isMicrosoft: true,
        details: 'The essential first step before building any Azure AI solution.',
        prerequisites: ['Azure Basics'],
      },
    ],
  },
  {
    id: 'ai-genai',
    title: 'AI & Generative AI',
    description: 'Master the future of technology with courses on LLMs, Copilot.',
    courses: [
      {
        id: 'ai-intro',
        title: 'Introduction to AI',
        topics: ['AI Concepts', 'Machine Learning', 'Azure Services', 'AI Solutions'],
        level: CourseLevel.Beginner,
        link: 'https://learn.microsoft.com/training/paths/introduction-to-ai-on-azure/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        details: 'Get started with Artificial Intelligence on Azure.',
        prerequisites: ['No prior experience required'],
      },
      {
        id: 'ai-genai-intro',
        title: 'Introduction to Generative AI and Agents',
        topics: ['Generative AI', 'LLMs', 'Prompting', 'AI Agents', 'Agentic AI'],
        level: CourseLevel.Beginner,
        link: 'https://learn.microsoft.com/training/modules/fundamentals-generative-ai/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        details: 'Explore the fundamentals of Generative AI.',
        prerequisites: ['No prior experience required'],
      },
      {
        id: 'ai-eng',
        title: 'Microsoft Certified:AI Engineer Associate',
        topics: ['Azure AI Services', 'NLP', 'Computer Vision', 'Generative AI', 'AI Solutions'],
        level: CourseLevel.Intermediate,
        link: 'https://learn.microsoft.com/credentials/certifications/azure-ai-engineer/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        details: 'The official certification page.',
        prerequisites: ['AI-102 Skills', 'Experience with Azure'],
      }
    ]
  },
  {
    id: 'machine-learning',
    title: 'Micorsoft Machine Learning',
    description: 'Build, train, and deploy models using Azure Machine Learning and Python.',
    courses: [
      {
        id: 'ml-concepts',
        title: 'Introduction to Machine Learning Concepts',
        topics: ['ML Fundamentals', 'ML Types', 'Training/Evaluation', 'Deep Learning'],
        level: CourseLevel.Beginner,
        link: 'https://learn.microsoft.com/training/modules/fundamentals-machine-learning/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        details: 'Understand the core principles of ML.',
        prerequisites: ['Basic Math'],
        isRecommended: true,
      },
      {
        id: 'ml-create',
        title: 'Create Machine Learning Models',
        topics: ['Regression', 'Classification', 'Clustering', 'Deep Learning'],
        level: CourseLevel.Intermediate,
        link: 'https://learn.microsoft.com/training/paths/create-machine-learn-models/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        details: 'Hands-on labs using Python to train models.',
        prerequisites: ['Python', 'Basic ML Concepts'],
      },
      {
        id: 'ml-pipeline',
        title: 'Run pipelines in Azure Machine Learning',
        topics: ['ML Pipelines', 'Automation', 'Components', 'Workflow Orchestration'],
        level: CourseLevel.Beginner,
        link: 'https://learn.microsoft.com/training/modules/run-pipelines-azure-machine-learning/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        details: 'Automate your workflows by connecting data prep.',
        prerequisites: ['Azure ML Workspace'],
      },
      {
        id: 'ml-cert',
        title: 'Microsoft Certified: Data Scientist Associate',
        topics: ['Data Science', 'ML Models', 'MLflow', 'Azure AI Services', 'Python'],
        level: CourseLevel.Intermediate,
        link: 'https://learn.microsoft.com/credentials/certifications/azure-data-scientist/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        details: 'Certification path for data scientists.',
        prerequisites: ['DP-100 Skills'],
      }
    ]
  },
  {
    id: 'python',
    title: 'Python on Azure & VS Code',
    description: 'From basics to advanced data analysis and intelligent apps.',
    courses: [
      {
        id: 'py-analyze',
        title: 'Explore and analyze data with Python',
        topics: ['Data Exploration', 'NumPy', 'Pandas', 'Matplotlib', 'Data Analysis'],
        level: CourseLevel.Intermediate,
        link: 'https://learn.microsoft.com/training/modules/explore-analyze-data-with-python/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        details: 'Use Jupyter notebooks to manipulate large datasets.',
        prerequisites: ['Python Syntax'],
      },
      {
        id: 'py-vs',
        title: 'Python Development with Visual Studio',
        topics: ['Python Development', 'Visual Studio IDE', 'Python Apps', 'Debugging'],
        level: CourseLevel.Beginner,
        link: 'https://learn.microsoft.com/visualstudio/python/?view=visualstudio?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        details: 'Set up Visual Studio 2022 for Python development.',
        prerequisites: ['No prior experience required'],
      },
      {
        id: 'py-copilot',
        title: 'Using GitHub Copilot with Python',
        topics: ['GitHub Copilot', 'AI Pair Programming', 'Python Development'],
        level: CourseLevel.Beginner,
        link: 'https://learn.microsoft.com/training/modules/introduction-copilot-python/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        details: 'Boost productivity by using AI to generate code snippets.',
        prerequisites: ['Basic Coding Knowledge'],
      },
      {
        id: 'py-apps',
        title: 'Build intelligent apps with Python',
        topics: ['Python', 'Azure', 'Cloud Computing', 'Intelligent Applications'],
        level: CourseLevel.Beginner,
        link: 'https://learn.microsoft.com/shows/azure-essentials-show/build-intelligent-apps-with-python?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        details: 'Video series on integrating Azure AI services.',
        prerequisites: ['Web Dev Basics', 'Python'],
      }
    ]
  },
  {
    id: 'web-dev',
    title: 'Web Dev with MS Tools',
    description: 'Modern web technologies including React, Node.js, and ASP.NET Core.',
    courses: [
      {
        id: 'web-start',
        title: 'Get started with web development using Visual Studio Code',
        topics: ['HTML', 'CSS', 'JavaScript', 'Web Development', 'Browser DevTools'],
        level: CourseLevel.Beginner,
        link: 'https://learn.microsoft.com/training/modules/get-started-with-web-development/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        details: 'Build your first static website using VS Code.',
        prerequisites: ['No prior experience required'],
      },
      {
        id: 'web-html',
        title: 'Build web pages with HTML and CSS for beginners',
        topics: ['HTML', 'CSS', 'Web Pages', 'VS Code', 'Web Accessibility'],
        level: CourseLevel.Beginner,
        link: 'https://learn.microsoft.com/training/paths/build-web-pages-html-css-for-beginners/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        details: 'Deep dive into semantic HTML tags and CSS styling.',
        prerequisites: ['No prior experience required'],
      },
    ]
  },
  {
    id: 'csharp',
    title: 'C# & .NET Development',
    description: 'Core fundamentals for building robust applications on the .NET platform.',
    courses: [
      {
        id: 'cs-write',
        title: 'Write your first C# code',
        topics: ['C# Basics', 'Console Applications', 'Syntax', 'First Code'],
        level: CourseLevel.Beginner,
        link: 'https://learn.microsoft.com/training/modules/csharp-write-first/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        details: 'Focuses on syntax precision and compilation.',
        prerequisites: ['No prior experience required'],
      },
    ]
  },
  {
    id: 'cloud',
    title: 'Azure Cloud Computing',
    description: 'Essential knowledge for cloud computing and infrastructure.',
    courses: [
      {
        id: 'cloud-intro',
        title: 'Introduction to Cloud Infrastructure',
        topics: ['Cloud Computing', 'Shared Responsibility Model', 'Azure Basics'],
        level: CourseLevel.Beginner,
        isRecommended: true,
        link: 'https://learn.microsoft.com/training/paths/microsoft-azure-fundamentals-describe-cloud-concepts/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        details: 'Explains IaaS, PaaS, SaaS models.',
        prerequisites: ['No prior experience required'],
      },
      {
        id: 'cloud-az900',
        title: 'Microsoft Azure Fundamentals (AZ-900)',
        topics: ['Azure Fundamentals', 'Cloud Services', 'Certification Prep'],
        level: CourseLevel.Beginner,
        link: 'https://learn.microsoft.com/credentials/certifications/resources/study-guides/az-900?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        details: 'Study guide for the AZ-900 exam.',
        prerequisites: ['No prior experience required'],
      },
    ]
  },
  {
    id: 'data-eng',
    title: 'Data Engineering',
    description: 'Pipelines, data storage, and analytics on the Azure platform.',
    courses: [
      {
        id: 'de-dp203',
        title: 'Data Engineering(DP-203T00)',
        topics: ['Data Engineering', 'Azure Synapse', 'Azure Databricks', 'Data Pipelines'],
        level: CourseLevel.Intermediate,
        link: 'https://learn.microsoft.com/training/courses/dp-203t00?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        details: 'Design and implement data storage using Azure Synapse.',
        prerequisites: ['SQL', 'Python/Scala', 'Azure Fundamentals'],
      }
    ]
  },
  {
    id: 'cyber-security',
    title: 'Cyber Security',
    description: 'Protect systems, networks, and programs from digital attacks using Microsoft Security solutions.',
    courses: [
      {
        id: 'sc-900',
        title: 'Microsoft Security, Compliance, and Identity Fundamentals',
        topics: ['Security Concepts', 'Identity Management', 'Compliance', 'Microsoft Entra ID'],
        level: CourseLevel.Beginner,
        link: 'https://learn.microsoft.com/credentials/certifications/security-compliance-and-identity-fundamentals/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        details: 'Learn the fundamentals of security, compliance, and identity.',
        prerequisites: ['No prior experience required'],
      },
      {
        id: 'sc-200',
        title: 'Microsoft Security Operations Analyst',
        topics: ['Threat Protection', 'Microsoft Sentinel', 'Defender for Cloud', 'KQL'],
        level: CourseLevel.Intermediate,
        link: 'https://learn.microsoft.com/credentials/certifications/security-operations-analyst/?WT.mc_id=academic&wt.mc_id=studentamb_508209',
        details: 'Learn to mitigate threats using Microsoft Sentinel.',
        prerequisites: ['SC-900 Skills', 'Basic Scripting'],
      }
    ]
  }
];
